apiVersion: v1
kind: Service
metadata:
  name: service-user
spec:
  type: LoadBalancer
  selector:
    app: service-user-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local